"""agrega descuento a producto

Revision ID: 4ff3740c2b40
Revises: ab71c68efd34
Create Date: 2026-06-15 20:06:33.600898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff3740c2b40'
down_revision: Union[str, Sequence[str], None] = 'ab71c68efd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('descuento', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'descuento')
    # ### end Alembic commands ###
