"""initial

Revision ID: ab71c68efd34
Revises: 
Create Date: 2026-06-15 19:05:03.839340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab71c68efd34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barrio_id'), 'barrio', ['id'], unique=False)
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localidad_id'), 'localidad', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ganancia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('es_relleno', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincia_id'), 'provincia', ['id'], unique=False)
    op.create_table('unidad_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidad_medida_id'), 'unidad_medida', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('numero_documento', sa.BigInteger(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('celular', sa.BigInteger(), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrio.id'], ),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidad.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cliente_documento', 'cliente', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('costo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingrediente_id'), 'ingrediente', ['id'], unique=False)
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_id'), 'receta', ['id'], unique=False)
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_id'), 'venta', ['id'], unique=False)
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_venta_id'), 'detalle_venta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_venta_id'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    op.drop_index(op.f('ix_venta_id'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_receta_id'), table_name='receta')
    op.drop_table('receta')
    op.drop_index(op.f('ix_ingrediente_id'), table_name='ingrediente')
    op.drop_table('ingrediente')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_index('ix_cliente_documento', table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_unidad_medida_id'), table_name='unidad_medida')
    op.drop_table('unidad_medida')
    op.drop_index(op.f('ix_provincia_id'), table_name='provincia')
    op.drop_table('provincia')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_localidad_id'), table_name='localidad')
    op.drop_table('localidad')
    op.drop_index(op.f('ix_barrio_id'), table_name='barrio')
    op.drop_table('barrio')
    # ### end Alembic commands ###
